export const INCREMENT_NUMBER_OF_REQUESTS_MADE = 'INCREMENT_NUMBER_OF_REQUESTS_MADE';

export const GET_WEATHER_FOR_CITY             = 'GET_WEATHER_FOR_CITY';
export const GET_WEATHER_FOR_CITY_SUCCESSFUL  = 'GET_WEATHER_FOR_CITY_SUCCESSFUL';
export const GET_WEATHER_FOR_CITY_FAILURE     = 'GET_WEATHER_FOR_CITY_FAILURE';
